excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://ericleib.github.io
title: Eric Leibenguth
email: eric.leibenguth@gmail.com
author: Eric Leibenguth
description: Professional Blog
paginate: 50
google_analytics: UA-60237395-4
bio: Aircraft Design, Software Development, Machine Learning & Robotics. I love all kind of machines, flying, walking or on wheels, real or simulated, preferably autonomous.<br>Enjoy the read & tell me what you think.
gems:
  - jekyll-redirect-from
  
