excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://ericleib.github.io
title: Eric Leibenguth
email: eric.leibenguth@gmail.com
author: Eric Leibenguth
description: Professional Blog
paginate: 50
google_analytics: UA-60237395-4
